### ISSUE TITLE
create 'RecipeCardVerticalSimple'

### ISSUE THREAD

**Issue by gerardogaravito** [gerardogaravito/team_cesar_c5#33]

**Comment by gerardogaravito** [comment]
![Captura de Pantalla 2020-08-28 a la(s) 16 49 06](https://user-images.githubusercontent.com/67488202/91617782-65a11d80-e94e-11ea-977b-78ef5d0a12c1.png)

**Comment by joseluiscaicedo** [comment]
add RecipeCardVerticalSimple and css style
