### ISSUE TITLE
create 'RecipeCardCuadradoInfo'

### ISSUE THREAD

**Issue by gerardogaravito** [gerardogaravito/team_cesar_c5#35]

**Comment by gerardogaravito** [comment]
![Captura de Pantalla 2020-08-28 a la(s) 16 48 19](https://user-images.githubusercontent.com/67488202/91617751-499d7c00-e94e-11ea-8a60-dbc0ca2c4081.png)

**Comment by joseluiscaicedo** [comment]
This component was create under the name "RecipeCardSquare"
