### ISSUE TITLE
Archivos repetidos (resolver conflictos)

### ISSUE THREAD

**Issue by R-Art-project** [gerardogaravito/team_cesar_c5#92]
<img width="310" alt="Screen Shot 2020-09-11 at 8 33 44 PM" src="https://user-images.githubusercontent.com/66227758/92984220-40dc9800-f46e-11ea-892f-55ab941757fd.png">
<img width="317" alt="Screen Shot 2020-09-11 at 8 33 54 PM" src="https://user-images.githubusercontent.com/66227758/92984221-41752e80-f46e-11ea-9a40-8ed3c3add933.png">
<img width="883" alt="Screen Shot 2020-09-11 at 8 34 00 PM" src="https://user-images.githubusercontent.com/66227758/92984222-420dc500-f46e-11ea-9998-94e8c74051f6.png">

**Comment by joseluiscaicedo** [comment]
fixed file conflicts
