### ISSUE TITLE
Create Recipe page

### ISSUE THREAD

**Issue by R-Art-project** [gerardogaravito/team_cesar_c5#95]
R-Art-project

**Comment by R-Art-project** [comment]
![Recet page](https://user-images.githubusercontent.com/66227758/93006902-aa6cad00-f527-11ea-9a59-00810c086f33.jpg)

**Comment by gerardogaravito** [comment]
Change the multiple photos to only one photo per recipe

![Captura de Pantalla 2020-09-17 a la(s) 16 44 53](https://user-images.githubusercontent.com/67488202/93531668-3c4c2f80-f905-11ea-9a13-79b4f915c631.png)
